openapi: '3.1.0'

info:
  title: API仕様書
  # description: 'APIバージョン: v1'
  description:
    $ref: ./info-description.md
  # termsOfService: ''
  # contact:
  #   name: ''
  #   url: ''
  #   email: ''
  # license:
  #   name: ''
  #   url: ''
  version: '1.0.0'

servers:
  - url: http://127.0.0.1:3000/api/v1
    description: ローカル通信
  - url: https://example.com:100000/api/v1
    description: リバースプロキシ経由(Production)

paths:
  /users:
    $ref: ./api/users.yaml#/paths/~1users

  /users/{id}:
    $ref: ./api/users.yaml#/paths/~1users~1{id}

components:
  schemas:
    Token:
      description: JSONWebトークン共通仕様
      type: object
      properties:
        token:
          type: string
        expires:
          type: string
          format: date-time
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZWJhYzUzNDk1NGI1NDEzOTgwNmMxMTIiLCJpYXQiOjE1ODkyOTg0ODQsImV4cCI6MTU4OTMwMDI4NH0.m1U63blB0MLej_WfB7yC2FTMnCziif9X8yzwDEfJXAg
        expires: 2020-05-12T16:18:04.793Z

    AuthTokens:
      description: 認証トークン
      type: object
      properties:
        access:
          $ref: '#/components/schemas/Token'
        refresh:
          $ref: '#/components/schemas/Token'

    Error:
      description: エラーレスポンススキーマ(共通)
      type: object
      properties:
        code:
          type: number
        message:
          type: string
        details:
          type: array
          items:
            - code:
                type: number
              message:
                type: string

  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 401
            message: 認証が必要です。

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 403
            message: 操作が許可されていません。

    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 404
            message: 指定されたリソースが存在しません。

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 500
            message: サーバ内部エラーが発生しました。

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
